name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Tailscale
        run: |
          sudo apt-get update
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no dev@100.64.236.62 'echo "SSH connection successful"'

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no dev@100.64.236.62 'bash /home/dev/deploy.sh'
